---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mypod
  name: mypod-taint-tol
spec:
  containers:
  - image: nginx:latest
    name: con1
    ports:
    - containerPort: 80
  tolerations:
  - key: "taint"
    operator: "Equal"
    value: "green"
    effect: NoExecute
