---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mypod
  name: to-master
spec:
  containers:
  - image: nginx:latest
    name: con1
    ports:
    - containerPort: 80
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: "Exists"
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: "Exists"
    effect: NoSchedule




